# Generated by Django 5.0.1 on 2024-01-22 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RJProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=50)),
                ('phone_number', models.IntegerField()),
                ('picture', models.ImageField(upload_to='RJ Profile')),
                ('biography', models.TextField()),
                ('facebook_profile', models.CharField(blank=True, max_length=200, null=True)),
                ('insta_profile', models.CharField(blank=True, max_length=200, null=True)),
                ('linkedin_profile', models.CharField(blank=True, max_length=200, null=True)),
                ('x_profile', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
