# Generated by Django 5.0.1 on 2024-01-23 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0002_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='show'),
        ),
    ]
