# Generated by Django 5.0.1 on 2024-01-31 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0003_show_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='sound',
            field=models.FileField(blank=True, default=None, null=True, upload_to='sound'),
        ),
    ]
