# Generated by Django 5.0.1 on 2024-02-01 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=80)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=80)),
                ('website', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
    ]
