# Generated by Django 5.0.1 on 2024-01-20 19:19

import django_quill.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blog_descriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='descriptions',
            field=django_quill.fields.QuillField(),
        ),
    ]
